# Site settings
title: Eduardo Spiegel's Research Page
description: >-
  Research work and projects in Graph Neural Networks, 
  focusing on Graph Transformers and Neural Collapse phenomena.
baseurl: "" # If your site is in a subdirectory, put it here
url: "" # Put your site's URL here

# Author settings
author:
  name: Eduardo Spiegel
  email: espiegel@ucsd.edu

# Theme settings
remote_theme: just-the-docs/just-the-docs

# Just the Docs specific settings
heading_anchors: true
color_scheme: light
search_enabled: true
aux_links:
  "Contact":
    - "mailto:espiegel@ucsd.edu"

# Navigation
nav_external_links:
  - title: UCSD
    url: https://ucsd.edu
    hide_icon: false

# Footer content
footer_content: "Mentored by Yusu Wang and Gal Mishne | Section A16"

# Collections (if you want to organize your content)
collections:
  projects:
    output: true
    permalink: /:collection/:path/

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md