# Site settings
title: Eduardo Spiegel's Research Page
description: Research in Graph Neural Networks and Neural Collapse at UCSD
author:
  name: Eduardo Spiegel
  email: espiegel@ucsd.edu

# Build settings
theme: minima
markdown: kramdown

# Theme customization
minima:
  date_format: "%b %-d, %Y"

# Header pages
header_pages:
 - about.md

# Show excerpts on the home page
show_excerpts: false