# Site settings
title: Eduardo Spiegel's Research Page
description: Research in Graph Neural Networks and Neural Collapse at UCSD
author:
  name: Eduardo Spiegel
  email: espiegel@ucsd.edu

# Build settings
theme: minima
markdown: kramdown

# Theme customization
minima:
  date_format: "%b %-d, %Y"

# Header pages
header_pages:
  - about.md

# Homepage settings
home_title: "Home"  # This will override the first heading on the homepage
page_excerpts: false
show_excerpts: false
list_title: null     # This removes the "Posts" heading if you don't have any posts